name: carousel_animations
description: swiper/carousel for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS. Has some fixes compared to original
version: 0.0.4
homepage: https://github.com/cbolich/carousel_animation

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4"

dev_dependencies:
  flutter_lints_plus: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
